---
title: ProLocker
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
facebookUrl: https://www.facebook.com/prolocker1
twitterUrl: https://twitter.com/prolocker1
youtubeUrl: https://www.youtube.com/channel/UCt-6_zL7KFsJkTkplCI1wfA
instagramUrl: https://www.instagram.com/prolocker/
snapChatUrl: https://www.snapchat.com/add/prolocker
